### ISSUE TITLE
run_call.pl error

### ISSUE THREAD

**Issue by bioinfo11** [iqbal-lab/cortex#16]
Hi Iqbal-lab,

I'm trying to run the 'Samples to VCF with the run calls wrapper'. Below is the command, error and file contents.

***COMMAND***
/path/to/CORTEX_release_v1.0.5.17/scripts/calling/run_calls.pl --first_kmer 31 --fastaq_index /path/to/index --auto_cleaning yes --bc yes --pd no --outdir ref_output --outvcf vcf_output --ploidy 1 --stampy_hash stampy_refhash --stampy_bin /path/to/stampy-1.0.22/stampy.py --list_ref_fasta list_full_genome_fasta --refbindir /path/to/ref.fasta --genome_size 2800000 --qthresh 5 --mem_height 17 --mem_width 100 --vcftools_dir path/to/vcftools_0.1.11/ --do_union yes --ref CoordinatesAndInCalling --workflow independent --logfile logfile_output log.txt

***ERROR***
returns 1 P8W_pe2 unexpected at /path/to/CORTEX_release_v1.0.5.17/scripts/calling/run_calls.pl line 2042, SAM line 1.

***INDEX***
P8W	.	P8W_pe1	P8W_pe2

***P8W_pe1***
P8_R1.fq

***P8W_pe2***
P8_R2.fq

If you had any advice that would be great.

Many thanks

**Comment by bioinfo11** [comment]
I've not fixed the error by adding the path to each file in the index and _pe1 and _pe2 files.

**Comment by iqbal-lab** [comment]
OK,apologies for not spotting this issue when you raised it
