### ISSUE TITLE
Please tag a release. Pretty please?

### ISSUE THREAD

**Issue by tseemann** [iqbal-lab/cortex#21]
Just go here https://github.com/iqbal-lab/cortex/releases and tag a release `1.0.5.21` please?

**Comment by tseemann** [comment]
Ping.

**Comment by iqbal-lab** [comment]
Thanks for the ping @tseemann . OK will do. Also "about" to start advocating the use of Cortex within a wrapper we've been building, with associated singularity container.

**Comment by iqbal-lab** [comment]
Done.
