### ISSUE TITLE
Add GFA support

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab/cortex#3]
See https://github.com/pmelsted/GFA-spec

**Comment by noporpoise** [comment]
GFA output is already in [McCortex](https://github.com/mcveanlab/mccortex), so the following will work with Cortex graphs:

    mccortex31 unitigs --gfa graph.ctx > graph.gfa

**Comment by iqbal-lab** [comment]
That's a great workaround for now, thanks!

**Comment by noporpoise** [comment]
BTW You can create a GFA file from a sequence file without writing the Cortex graph file to disk:

    mccortex31 build -k 31 -s Example --seq in.fa - | mccortex31 unitigs --gfa - > graph.gfa

**Comment by iqbal-lab** [comment]
Hurrah for Mccortex! Thanks Isaac.

**Comment by iqbal-lab** [comment]
Confirmed.
